Problem: Problem1.cpp
	g++ -Wall -g -o Problem Problem1.cpp

Test: Test.cpp
	g++ -Wall -g -o Test Test.cpp

clean:
	rm -f Problem
	rm -f Test

run: Problem
	./Problem

test: Test
	./Test